### ISSUE TITLE
Fortran output for very small numbers drops "e", C++ doesn't like that

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/initial_models#10]
For the initial models where the output is still written from Fortran, Fortran will write numbers smaller than 1.e-99 by dropping the `e`, e.g., as `0.6419309554625291-102`.  Our model parsers don't like this, and it messes up the model reading.

We should clip small values before outputting.

**Comment by aisclark91** [comment]
I have added a `cfmt.H` in `lagrangian_planar` to do exactly this.

**Comment by zingale** [comment]
I think that this has been resolved
